//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_pass
    {
        public int User_ID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_worker { get; set; }
        public int admin { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
