//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class course_workEntities : DbContext
    {
        public course_workEntities()
            : base("name=course_workEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application_for_vacation> Application_for_vacation { get; set; }
        public virtual DbSet<Classification_vacation> Classification_vacation { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<log_pass> log_pass { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<Workers_on_project> Workers_on_project { get; set; }
    }
}
