//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Workers_on_project = new HashSet<Workers_on_project>();
        }
    
        public int id_project { get; set; }
        public string project_name { get; set; }
        public System.DateTime date_project_begin { get; set; }
        public System.DateTime date_project_end { get; set; }
        public int labor_count { get; set; }
        public System.DateTime date_project_status { get; set; }
        public int project_manager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workers_on_project> Workers_on_project { get; set; }
    }
}
