//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int id_vacation { get; set; }
        public int id_application { get; set; }
        public int id_worker { get; set; }
        public System.DateTime data_vacation_real { get; set; }
        public int vacation_count_real { get; set; }
        public int id_classification_vacation { get; set; }
    
        public virtual Application_for_vacation Application_for_vacation { get; set; }
    }
}
