//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Application_for_vacation = new HashSet<Application_for_vacation>();
            this.log_pass = new HashSet<log_pass>();
            this.Workers_on_project = new HashSet<Workers_on_project>();
        }
    
        public int id_worker { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string service_number { get; set; }
        public Nullable<int> post { get; set; }
        public string Email { get; set; }
        public Nullable<int> phone { get; set; }
        public System.DateTime date_hiring { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> department { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_for_vacation> Application_for_vacation { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual gender gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_pass> log_pass { get; set; }
        public virtual Post Post1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workers_on_project> Workers_on_project { get; set; }
    }
}
