//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFrmw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers_on_project
    {
        public int id_worker_on_project { get; set; }
        public int id_project { get; set; }
        public int id_worker { get; set; }
        public string project_role { get; set; }
        public System.DateTime date_start_participate { get; set; }
        public System.DateTime date_end_participate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
